# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Slimefun DEV

on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk
          architecture: x64
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build Slimefun
        if: github.event_name != 'pull_request'
        run: mvn -B package --file pom.xml --errors
      - name: Publish Slimefun
        if: github.event_name != 'pull_request'
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --file pom-github-package.xml --errors
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Mask Output
        if: github.event_name != 'pull_request'
        run: |
          echo "::add-mask::$CF_API_TOKEN"
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - name: Find build artifact filename
        if: github.event_name != 'pull_request'
        run: |
          cd target && FILENAME=$(find . -maxdepth 1 -mindepth 1 -name "Slimefun-*" | cut -d'/' -f 2)
          echo "slimefun-artifact-name=$FILENAME" >> "$GITHUB_ENV"
          cd ..
      - name: Upload Build
        if: github.event_name != 'pull_request'
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: "r2 object put slimefun-dev/${{ env.slimefun-artifact-name }} --file=./target/${{ env.slimefun-artifact-name }} --content-type=application/java-archive"
